### ISSUE TITLE
Layout definitions are not valid in theme.json

### ISSUE THREAD

**Issue by carolinan** [tenman/emulsion#53]
Hi!
In theme.json, the layout > definitions are not valid.
In WordPress 6.3, these definitions will also be moved from the WordPress default theme.json.
Please see
https://core.trac.wordpress.org/ticket/58550

**Comment by tenman** [comment]
Thank you for your interest in the emulsion theme.
Sorry, I overlooked your issue.

For backward compatibility with WordPress 6.2, the layout/definitions setting was left in place, but now that 6.4 has been released, the definitions have been removed in emulsion 2.9.2.

thank you.
